# more detailed reference https://github.com/hfutrobocup3d/automatch/wiki/auto-match-params-configuration

basedir: /home/shan/2019
mainteam: HFUTEngine

masterHost: 172.17.0.1
masterPort: 8000
retrywait: 30

# choose: [sequent, random]
choose: sequent
record-fn: log/output.txt